name: product_dbt_pipeline
version: '1.0.0'
config-version: 2
profile: product_dbt_pipeline
model-paths: ["models"]
test-paths: ["tests"]

models:
  product_dbt_pipeline:
    staging:
      +materialized: view
    marts:
      +materialized: table
