SELECT
    PRODUCT_ID,
    TRIM(PRODUCT_NAME) AS PRODUCT_NAME,
    UPPER(TRIM(CATEGORY)) AS CATEGORY,
    UPPER(TRIM(SUBCATEGORY)) AS SUBCATEGORY,
    TRIM(BRAND) AS BRAND,
    PRICE,
    QUANTITY,
    DISCOUNT,
    ROUND(PRICE * QUANTITY, 2) AS GROSS_VALUE,
    ROUND(PRICE * QUANTITY * (1 - DISCOUNT), 2) AS NET_VALUE
FROM {{ source('raw', 'RAW_PRODUCTS') }}
